server:
  port: ${server.port}
  tomcat:
    threads:
      max: ${server.tomcat.threads.max}
    max-connections: ${server.tomcat.max-connections}
    accept-count: ${server.tomcat.accept-count}

spring:

  profiles:
    active: dev
  application:
    name: ${spring.application.name}
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}
    lettuce:
      pool:
        max-active: ${spring.redis.lettuce.pool.max-active}
        max-idle: ${spring.redis.lettuce.pool.max-idle}
        min-idle: ${spring.redis.lettuce.pool.min-idle}
        time-between-eviction-runs: ${spring.redis.lettuce.pool.time-between-eviction-runs}
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
    org.springframework.data.redis: WARN